set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(_LOCAL_XPACK_TOOLCHAIN "${CMAKE_CURRENT_LIST_DIR}/../../.tools/xpack-arm-none-eabi-gcc/bin")

if(EXISTS "${_LOCAL_XPACK_TOOLCHAIN}/arm-none-eabi-gcc")
  set(_ARM_TOOLCHAIN_PREFIX "${_LOCAL_XPACK_TOOLCHAIN}/arm-none-eabi-")
else()
  set(_ARM_TOOLCHAIN_PREFIX "arm-none-eabi-")
endif()

set(CMAKE_C_COMPILER "${_ARM_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_ASM_COMPILER "${_ARM_TOOLCHAIN_PREFIX}gcc")
set(CMAKE_OBJCOPY "${_ARM_TOOLCHAIN_PREFIX}objcopy" CACHE INTERNAL "")
set(CMAKE_SIZE "${_ARM_TOOLCHAIN_PREFIX}size" CACHE INTERNAL "")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
